# CMake generated Testfile for 
# Source directory: /Users/rishabnuguru/space
# Build directory: /Users/rishabnuguru/space
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(monte_carlo_validation "/Users/rishabnuguru/space/monte_carlo_validation")
set_tests_properties(monte_carlo_validation PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;301;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(space_monte_carlo_validation "/Users/rishabnuguru/space/space_monte_carlo_validation")
set_tests_properties(space_monte_carlo_validation PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;307;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(geo_mission_validation "/Users/rishabnuguru/space/geo_mission_validation")
set_tests_properties(geo_mission_validation PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;316;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(geo_mission_shield_validation "/Users/rishabnuguru/space/geo_mission_shield_validation")
set_tests_properties(geo_mission_shield_validation PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;325;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(realistic_space_validation "/Users/rishabnuguru/space/realistic_space_validation")
set_tests_properties(realistic_space_validation PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;331;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(framework_verification_test "/Users/rishabnuguru/space/framework_verification_test")
set_tests_properties(framework_verification_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;336;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(enhanced_tmr_test "/Users/rishabnuguru/space/enhanced_tmr_test")
set_tests_properties(enhanced_tmr_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;340;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(scientific_validation_test "/Users/rishabnuguru/space/scientific_validation_test")
set_tests_properties(scientific_validation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;357;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(radiation_stress_test "/Users/rishabnuguru/space/radiation_stress_test")
set_tests_properties(radiation_stress_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;361;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(systematic_fault_test "/Users/rishabnuguru/space/systematic_fault_test")
set_tests_properties(systematic_fault_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;365;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(modern_features_test "/Users/rishabnuguru/space/modern_features_test")
set_tests_properties(modern_features_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;369;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(enhanced_quantum_integration_test "/Users/rishabnuguru/space/enhanced_quantum_integration_test")
set_tests_properties(enhanced_quantum_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;375;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(radiation_intensity_aggregation_test "/Users/rishabnuguru/space/radiation_intensity_aggregation_test")
set_tests_properties(radiation_intensity_aggregation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;381;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(relativistic_cascade_test "/Users/rishabnuguru/space/relativistic_cascade_test")
set_tests_properties(relativistic_cascade_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;387;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(simple_enhanced_test "/Users/rishabnuguru/space/simple_enhanced_test")
set_tests_properties(simple_enhanced_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;392;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(ieee754_tmr_test "/Users/rishabnuguru/space/ieee754_tmr_test")
set_tests_properties(ieee754_tmr_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;398;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(quantum_field_validation_test "/Users/rishabnuguru/space/quantum_field_validation_test")
set_tests_properties(quantum_field_validation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;407;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(realistic_leo_mission_test "/Users/rishabnuguru/space/realistic_leo_mission_test")
set_tests_properties(realistic_leo_mission_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;416;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(ml_radiation_training_test "/Users/rishabnuguru/space/ml_radiation_training_test")
set_tests_properties(ml_radiation_training_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;468;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(cross_validation_test "/Users/rishabnuguru/space/cross_validation_test")
set_tests_properties(cross_validation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;487;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(training_loop_diagnostic "/Users/rishabnuguru/space/training_loop_diagnostic")
set_tests_properties(training_loop_diagnostic PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;506;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(simple_radiation_test "/Users/rishabnuguru/space/simple_radiation_test")
set_tests_properties(simple_radiation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;525;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(weight_diagnostic_test "/Users/rishabnuguru/space/weight_diagnostic_test")
set_tests_properties(weight_diagnostic_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;544;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(trained_network_radiation_test "/Users/rishabnuguru/space/trained_network_radiation_test")
set_tests_properties(trained_network_radiation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;563;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(trivial_radiation_test "/Users/rishabnuguru/space/trivial_radiation_test")
set_tests_properties(trivial_radiation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;582;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(lmdb_basic_test "/Users/rishabnuguru/space/lmdb_basic_test")
set_tests_properties(lmdb_basic_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;674;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(lmdb_datacenter_demo "/Users/rishabnuguru/space/lmdb_datacenter_demo")
set_tests_properties(lmdb_datacenter_demo PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;688;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(ai_native_database_test "/Users/rishabnuguru/space/ai_native_database_test")
set_tests_properties(ai_native_database_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;829;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
add_test(simple_ai_database_test "/Users/rishabnuguru/space/simple_ai_database_test")
set_tests_properties(simple_ai_database_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/CMakeLists.txt;842;add_test;/Users/rishabnuguru/space/CMakeLists.txt;0;")
subdirs("src/tmr")
subdirs("src/rad_ml/research")
subdirs("examples")
