# CMake generated Testfile for 
# Source directory: /Users/rishabnuguru/space/examples
# Build directory: /Users/rishabnuguru/space/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(architecture_test_run "/Users/rishabnuguru/space/examples/architecture_test")
set_tests_properties(architecture_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;211;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(residual_network_test_run "/Users/rishabnuguru/space/examples/residual_network_test")
set_tests_properties(residual_network_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;212;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(auto_arch_search_example_run "/Users/rishabnuguru/space/examples/auto_arch_search_example")
set_tests_properties(auto_arch_search_example_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;213;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(adaptive_mutation_test_run "/Users/rishabnuguru/space/examples/adaptive_mutation_test")
set_tests_properties(adaptive_mutation_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;214;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(adaptive_mutation_demo_run "/Users/rishabnuguru/space/examples/adaptive_mutation_demo")
set_tests_properties(adaptive_mutation_demo_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;215;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(radiation_aware_training_example_run "/Users/rishabnuguru/space/examples/radiation_aware_training_example")
set_tests_properties(radiation_aware_training_example_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;216;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(multi_particle_simulation_example_test "/Users/rishabnuguru/space/examples/multi_particle_simulation_example")
set_tests_properties(multi_particle_simulation_example_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;217;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(vae_example_run "/Users/rishabnuguru/space/examples/vae_example")
set_tests_properties(vae_example_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;218;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(vae_space_mission_test_run "/Users/rishabnuguru/space/examples/vae_space_mission_test")
set_tests_properties(vae_space_mission_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;219;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(vae_validation_test_run "/Users/rishabnuguru/space/examples/vae_validation_test")
set_tests_properties(vae_validation_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;220;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(vae_production_example_run "/Users/rishabnuguru/space/examples/vae_production_example")
set_tests_properties(vae_production_example_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;221;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(vae_comprehensive_test "/Users/rishabnuguru/space/examples/vae_comprehensive_test")
set_tests_properties(vae_comprehensive_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;222;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(vae_monte_carlo_tuning_example_run "/Users/rishabnuguru/space/examples/vae_monte_carlo_tuning_example")
set_tests_properties(vae_monte_carlo_tuning_example_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;223;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(quantum_enhanced_radiation_test_run "/Users/rishabnuguru/space/examples/quantum_enhanced_radiation_test")
set_tests_properties(quantum_enhanced_radiation_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;224;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(compression_validation_test_run "/Users/rishabnuguru/space/examples/compression_validation_test")
set_tests_properties(compression_validation_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;225;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
add_test(large_dataset_compression_test_run "/Users/rishabnuguru/space/examples/large_dataset_compression_test")
set_tests_properties(large_dataset_compression_test_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/rishabnuguru/space/examples/CMakeLists.txt;226;add_test;/Users/rishabnuguru/space/examples/CMakeLists.txt;0;")
subdirs("simple_nn")
subdirs("mission_simulator")
